 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package PacoteHerdadoConta;
public abstract class Conta {
  
  protected double saldo;
  
  private int agencia;
  
  private int numero;
  
  private PacoteHerdadoConta.Cliente titular;
  
  private static int total;
  
  public Conta(int agencia, int numero) {
  }
  
  public abstract void deposita(double arg0);
  
  public void saca(double valor) throws SaldoInsuficienteException {
    if(this.saldo < valor) {
    	
    	throw new SaldoInsuficienteException("Saldo: " + this.saldo + ", Valor: " + valor);
    	
    }
    
    	this.saldo -= valor;
  }
  
  public void transfere(double valor, Conta destino) throws SaldoInsuficienteException {
    this.saca(valor);
    destino.deposita(valor);
  }
  
  public double getSaldo() {
    return this.saldo;
  }
  
  public int getNumero() {
    return this.numero;
  }
  
  public void setNumero(int numero) {
  }
  
  public int getAgencia() {
    return this.agencia;
  }
  
  public void setAgencia(int agencia) {
  }
  
  public PacoteHerdadoConta.Cliente getTitular() {
    return null;
  }
  
  public void setTitular(PacoteHerdadoConta.Cliente titular) {
  }
  
  public static int getTotal() {
    return 0;
  }
  
  public static void setTotal(int total) {
  }
}