 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package PacoteHerdadoConta;
public class SeguroDeVida implements PacoteHerdadoConta.Tributavel {
  
  public SeguroDeVida() {
  }
  
  public double getValorImposto() {
    return 0;
  }
}