 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package PacoteHerdadoConta;
public class TesteTributaveis {
  
  public TesteTributaveis() {
  }
  
  public static void main(java.lang.String[] args) {
  }
}