 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package br.com.bradesco.banco.modelo;
public class CalculadorDeImposto {
  
  private double totalImposto;
  
  public CalculadorDeImposto() {
  }
  
  public void registra(Tributavel tributavel) {
  }
  
  public double getTotalImposto() {
    return 0;
  }
}