 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package br.com.bradesco.banco.modelo;
public class Cliente {
  
  private java.lang.String nome;
  
  private java.lang.String cpf;
  
  private java.lang.String profissao;
  
  Cliente(java.lang.String nome, java.lang.String cpf, java.lang.String profissao) {
  }
  
  public java.lang.String getNome() {
    return null;
  }
  
  public void setNome(java.lang.String nome) {
  }
  
  public java.lang.String getCpf() {
    return null;
  }
  
  public void setCpf(java.lang.String cpf) {
  }
  
  public java.lang.String getProfissao() {
    return null;
  }
  
  public void setProfissao(java.lang.String profissao) {
  }
}