 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package br.com.bradesco.banco.modelo;



public class TesteTributaveis {
  
  public TesteTributaveis() {
  }
  
  public static void main(java.lang.String[] args) throws SaldoInsuficienteException {
  
	  ContaCorrente cc= new ContaCorrente(222, 333);
	  cc.deposita(100.0);
	  
	  SeguroDeVida seguro = new SeguroDeVida();
	  
	  CalculadorDeImposto calc = new CalculadorDeImposto();
	  calc.registra(cc);
	  calc.registra(seguro);
	  
	  System.out.println(calc.getTotalImposto());
  
  
  }
}