 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package br.com.bradesco.banco.modelo;

import br.com.bradesco.banco.especial.ContaEspecial;

public class TesteConta {
  
  public TesteConta() {
  }
  
  public static void main(java.lang.String[] args) throws SaldoInsuficienteException {
	  
	  
	  
	  

	  //Full Qualified Name -> FQN = Nome Pacote . Nome Simples da Classe
	  ContaCorrente cc = new ContaCorrente(111, 111);
	  cc.deposita(100.0);
	  
	  ContaPoupanca cp = new ContaPoupanca(222, 222);
	  cp.deposita(200.0);
	  
	  System.out.println(cc.getSaldo());
	  System.out.println(cp.getSaldo());
	  
  }
} 