 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package br.com.bradesco.banco.modelo;
public abstract interface Tributavel {
  
  public abstract double getValorImposto();
}