 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package br.com.bradesco.banco.test;

import br.com.bradesco.banco.modelo.ContaCorrente;
import br.com.bradesco.banco.modelo.ContaPoupanca;
import br.com.bradesco.banco.modelo.SaldoInsuficienteException;



public class TesteConta {
	
  
  public TesteConta() {
  }
  
  public static void main(java.lang.String[] args) throws SaldoInsuficienteException{
	  
	  //Full Qualified Name -> FQN = Nome Pacote . Nome Simples da Classe
	  ContaCorrente cc = new ContaCorrente(111, 111);
	  cc.deposita(150.0);
	  
	  ContaPoupanca cp = new ContaPoupanca(222, 222);
	  cp.deposita(200.0);
	  
	  cc.saca(50.0);
	  cp.saca(150.0);
	  
	  System.out.println(cc.getSaldo());
	  System.out.println(cp.getSaldo());

	  
  }
} 