 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package br.com.bradesco.banco.test;

import br.com.bradesco.banco.modelo.SeguroDeVida;
import br.com.bradesco.banco.modelo.CalculadorDeImposto;
import br.com.bradesco.banco.modelo.ContaCorrente;


public class TesteTributaveis {
  
  public static void main(java.lang.String[] args) {
  
	  ContaCorrente contaGusta= new ContaCorrente(222, 333);
	  contaGusta.deposita(100.0);
	  
	  SeguroDeVida seguro = new SeguroDeVida();
	  
	  CalculadorDeImposto calc = new CalculadorDeImposto();
	  calc.registra(contaGusta);
	  calc.registra(seguro);
	  
	  System.out.println(calc.getTotalImposto());
  
  
  }
}